export default [

    {
    title: 'Rome in 264 a.C.',
    text: 'The Roman Republic had been aggressively expanding in the southern Italian mainland for a century before the First Punic War.[27] It had conquered peninsular Italy south of the River Arno by 272 BC, when the Greek cities of southern Italy (Magna Graecia) submitted at the conclusion of the Pyrrhic War. Adult male Roman citizens were eligible for military service, most would serve as infantry with the wealthier minority providing a cavalry component. Traditionally the Romans would raise two legions, each of 4,200 infantry[note 3] and 300 cavalry. A small number of the infantry served as javelin-armed skirmishers. The balance were equipped as heavy infantry, with body armour, a large shield, and short thrusting swords. They were divided into three ranks, of which the front rank also carried two javelins, while the second and third ranks had a thrusting spear instead. Both legionary sub-units and individual legionaries fought in relatively open order. An army was usually formed by combining a Roman legion with a similarly sized and equipped legion provided by their Latin allies.'
    },

    {
        title: 'Syracuse in 264 a.C.',
        text: 'Hiero II (Greek: Ἱέρων Β΄; c. 308 BC – 215 BC) was the Greek tyrant of Syracuse from 270 to 215 BC. He was a former general of Pyrrhus of Epirus and an important figure of the First Punic War.[1]. On the departure of Pyrrhus from Sicily (275 BC) the Syracusan army and citizens appointed him commander of the troops. He strengthened his position by marrying the daughter of Leptines, the leading citizen. In the meantime, the Mamertines, a body of Campanian mercenaries who had been employed by Agathocles, had seized the stronghold of Messina, and proceeded in harassing the Syracusans. They were finally defeated in a pitched battle near Mylae along the Longanus river by Hiero, who was only prevented from capturing Messina by Carthaginian interference. His grateful countrymen then made him king (270)'
    },

   {
        title: 'Carthage in 264 a.C.',
        text: 'During this period Carthage, with its capital in what is now Tunisia, had come to dominate southern Spain, much of the coastal regions of North Africa, the Balearic Islands, Corsica, Sardinia, and the western half of Sicily in a military and commercial empire.[29] Beginning in 480 BC, Carthage had fought a series of inconclusive wars against the Greek city states of Sicily, led by Syracuse.[30] By 264 BC Carthage and Rome were the preeminent powers in the western Mediterranean.[31] The two states had several times asserted their mutual friendship via formal alliances: in 509 BC, 348 BC and around 279 BC. Relationships were good, with strong commercial links. During the Pyrrhic War of 280–275 BC, against a king of Epirus who alternately fought Rome in Italy and Carthage on Sicily, Carthage provided materiel to the Romans and on at least one occasion used its navy to ferry a Roman force.[32][33]. Carthaginian citizens only served in their army if there was a direct threat to the city. In most circumstances Carthage recruited foreigners to make up its army. Many would be from North Africa which provided several types of fighters including: close-order infantry equipped with large shields, helmets, short swords and long thrusting spears; javelin-armed light infantry skirmishers; close-order shock cavalry carrying spears; and light cavalry skirmishers who threw javelins from a distance and avoided close combat.[47][48] Both Spain and Gaul provided small numbers of experienced infantry; unarmoured troops who would charge ferociously, but had a reputation for breaking off if a combat was protracted.[47][49][note 4] Most of the Carthaginian infantry would fight in a tightly-packed formation known as a phalanx, usually forming two or three lines.[48] Two thousand slingers were recruited from the Balearic Islands.[47][50] The Carthaginians also employed war elephants; North Africa had indigenous African forest elephants at the time.[49]'
    },

    {
        title: 'Messana in 264 a.C.',
        text: 'Messana had been conquered by the Mamertines, a group of disreputable mercenaries from Campania in Italy, in 288 BCE. Hard-pressed by Syracuse, the Mamertines appealed to both Rome and Carthage for assistance in 265 BC. The Carthaginians acted first, pressing Hiero II, king of Syracuse, into taking no further action and convincing the Mamertines to accept a Carthaginian garrison.[35] According to Polybius, a considerable debate then took place in Rome as to whether to accept the Mamertines appeal for assistance. As the Carthaginians had already garrisoned Messana acceptance could easily lead to war with Carthage. The Romans had not previously displayed any interest in Sicily and did not wish to come to the aid of soldiers who had unjustly stolen a city from its rightful possessors. However, many of them saw strategic and monetary advantages in gaining a foothold in Sicily. The deadlocked Roman Senate put the matter before the popular assembly in 264 BC, and it decided to accept the Mamertines request.[36][37] Appius Claudius Caudex was appointed commander of a military expedition with orders to cross to Sicily and place a Roman garrison in Messana.[38][39]'
    }
]
